### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by sailoog** [joabakk/signalk-vesselsetup-plugin#17]
**We are getting this in openplotter when installing:**

npm, ERR! Linux 4.9.35-v7+
,npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "signalk-vesselsetup-plugin"
,npm ,ERR! node v6.11.4
,npm, ERR! npm  v3.10.10
,npm ERR! code EREADFILE
,
,npm, ERR! Error extracting /home/pi/.npm/signalk-vesselsetup-plugin/0.4.3/package.tgz archive: ENOENT: no such file or directory, open '/home/pi/.npm/signalk-vesselsetup-plugin/0.4.3/package.tgz'
npm ERR! 
npm, ERR! If you need help, you may report this error at:
npm, ERR!     
,
,npm ERR! Please include the following file with any support request:
npm ERR!,     /home/pi/.config/signalk-server-node/npm-debug.log

**an this is npm-debug.log:**

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'signalk-vesselsetup-plugin' ]
2 info using npm@3.10.10
3 info using node@v6.11.4
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData signalk-vesselsetup-plugin
8 silly fetchNamedPackageData signalk-vesselsetup-plugin
9 silly mapToRegistry name signalk-vesselsetup-plugin
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'signalk-vesselsetup-plugin',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'signalk-vesselsetup-plugin',
12 silly mapToRegistry   name: 'signalk-vesselsetup-plugin',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/signalk-vesselsetup-plugin
14 verbose request uri https://registry.npmjs.org/signalk-vesselsetup-plugin
15 verbose request no auth needed
16 info attempt registry request try #1 at 6:49:28 PM
17 verbose request id 127bb112459e956c
18 http request GET https://registry.npmjs.org/signalk-vesselsetup-plugin
19 http 200 https://registry.npmjs.org/signalk-vesselsetup-plugin
20 verbose headers { server: 'nginx/1.10.1',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'last-modified': 'Sun, 01 Oct 2017 20:04:25 GMT',
20 verbose headers   etag: 'W/"59d14a49-4a85"',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '1976',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Thu, 12 Oct 2017 18:49:29 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-mad9434-MAD',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1507834169.081511,VS0,VE482',
20 verbose headers   vary: 'Accept-Encoding, Accept' }
21 silly get cb [ 200,
21 silly get   { server: 'nginx/1.10.1',
21 silly get     'content-type': 'application/json',
21 silly get     'last-modified': 'Sun, 01 Oct 2017 20:04:25 GMT',
21 silly get     etag: 'W/"59d14a49-4a85"',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '1976',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Thu, 12 Oct 2017 18:49:29 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-mad9434-MAD',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1507834169.081511,VS0,VE482',
21 silly get     vary: 'Accept-Encoding, Accept' } ]
22 verbose get saving signalk-vesselsetup-plugin to /home/pi/.npm/registry.npmjs.org/signalk-vesselsetup-plugin/.cache.json
23 verbose correctMkdir /home/pi/.npm correctMkdir not in flight; initializing
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly resolveWithNewModule signalk-vesselsetup-plugin@0.4.3 checking installable status
37 silly rollbackFailedOptional Starting
38 silly rollbackFailedOptional Finishing
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Error extracting /home/pi/.npm/signalk-vesselsetup-plugin/0.4.3/package.tgz archive: ENOENT: no such file or directory, open '/home/pi/.npm/signalk-vesselsetup-plugin/0.4.3/package.tgz'
41 verbose stack     at ReadStream.<anonymous> (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:309:10)
41 verbose stack     at emitOne (events.js:96:13)
41 verbose stack     at ReadStream.emit (events.js:188:7)
41 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:190:14
41 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:241:16
41 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
42 verbose cwd /home/pi/.config/signalk-server-node
43 error Linux 4.9.35-v7+
44 error argv "/usr/bin/node" "/usr/bin/npm" "install" "signalk-vesselsetup-plugin"
45 error node v6.11.4
46 error npm  v3.10.10
47 error code EREADFILE
48 error Error extracting /home/pi/.npm/signalk-vesselsetup-plugin/0.4.3/package.tgz archive: ENOENT: no such file or directory, open '/home/pi/.npm/signalk-vesselsetup-plugin/0.4.3/package.tgz'
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

**Comment by joabakk** [comment]
Very strange. I have seen this error reported before on another of my plugins, but I am not able to reproduce it with npm v3.10.9 and node v6.9.2

It may actually be an npm issue, see https://github.com/npm/npm/issues/18437

**Comment by luckbert** [comment]
Hello joabakk, 
I'm afraid I noticed the mistake. I'm using Openplotte 0.16.0. I'm not a programmer so I need precise help. I'd like to work with you. Do you have any idea what could be wrong? 
Greetings Jürgen

P. S.I come from Germany and my English is not so good. I have to run everything through a translator. :)

**Comment by joabakk** [comment]
I have cleaned up the package file and issued a new version 0.5.1 now. See if that helps

**Comment by luckbert** [comment]
Hi 
The installation has worked. I could make entries. 
I will test it at the next opportunity to see if my ship is shown on Marinetraffic. I hope I have entered all input correctly in the plugin. I still miss the category to which the ship belongs (SAR boat, sailboat, motor boat,...).
Thank you for your trouble. 
Greetings from Germany 
Jürgen 

Edit: How can I check if my data is sent to Marinetraffic?

**Comment by joabakk** [comment]
Thank you for reporting in. 
This plugin only populates the settings .json file for Signal K. For sending info to Marine Traffic, you should use @signalk/aisreporter

**Comment by luckbert** [comment]
okay, 
see [here.](http://forum.openmarine.net/showthread.php?tid=795&pid=3321#pid3321) I'm not getting anywhere.

**Comment by sailoog** [comment]
@luckbert, this is now an openplotter issue, let's treat this on OP forum. Thanks @joabakk.
