### ISSUE TITLE
Enable writing to interfaces as default

### ISSUE THREAD

**Issue by joabakk** [joabakk/signalk-vesselsetup-plugin#5]
NMEA0183 and N2K can be written to, if the settings are right.

**Comment by sbender9** [comment]
The antisense-serial execute provider should have 

```
          "toChildProcess": "nmea2000out"
```

Not sure about 0183

**Comment by joabakk** [comment]
From my notes I have  `"toStdout": "nmea0183out"`  after baudrate for 0183

**Comment by sbender9** [comment]
Yes, that's correct: https://github.com/SignalK/signalk-server-node/blob/master/providers/serialport.js#L59

**Comment by joabakk** [comment]
Thanks!
